/**
 * Shared helpers for the Reports / Feedback / Analytics module.
 */

/** Unwrap ApiResponse<{data}> / Page / raw arrays into a plain array. */
export function unwrapList(res) {
  if (Array.isArray(res)) return res;
  if (Array.isArray(res?.data)) return res.data;
  if (Array.isArray(res?.data?.content)) return res.data.content;
  if (Array.isArray(res?.content)) return res.content;
  return [];
}

/** Unwrap ApiResponse<T> into T. */
export function unwrapData(res) {
  return res && typeof res === 'object' && 'data' in res ? res.data : res;
}

/** NOMINATION -> Nomination, IN_PROGRESS -> In Progress */
export function humanize(value) {
  if (!value) return '—';
  return String(value)
    .toLowerCase()
    .split('_')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
}

/** Build a { id: name } lookup from a category list. */
export function buildCategoryMap(categories) {
  const map = {};
  (categories || []).forEach((c) => {
    map[c.id] = c.name || c.title || `Category #${c.id}`;
  });
  return map;
}

function triggerDownload(text, filename, mime) {
  const blob = new Blob([text], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

/**
 * Client-side download of a report's stored text content.
 * The backend stores `content` only (no binary generation), so:
 *  - CSV / EXCEL -> .csv (opens in Excel)
 *  - PDF / none  -> .txt with a metadata header
 */
export function downloadReport(report, categoryName) {
  const stamp = (report.createdAt || '').slice(0, 10) || 'undated';
  const base = `awardhub_${String(report.reportType || 'report').toLowerCase()}_${report.id}_${stamp}`;
  const content = report.content || '';

  if (report.format === 'CSV' || report.format === 'EXCEL') {
    triggerDownload(content, `${base}.csv`, 'text/csv;charset=utf-8');
    return;
  }

  const header = [
    `AwardHub Report #${report.id}`,
    `Type: ${humanize(report.reportType)}`,
    `Category: ${categoryName || (report.categoryId ? `#${report.categoryId}` : 'All categories')}`,
    `Format: ${report.format || '—'}`,
    `Generated by: ${report.generatedBy || '—'}`,
    `Created at: ${report.createdAt || '—'}`,
    `Archived: ${report.archived ? 'Yes' : 'No'}`,
    '----------------------------------------',
    '',
  ].join('\n');
  triggerDownload(header + content, `${base}.txt`, 'text/plain;charset=utf-8');
}
