import React from 'react';
import { Download } from 'lucide-react';
import Modal from '../ui/Modal';
import Button from '../ui/Button';
import StatusBadge from '../ui/StatusBadge';
import { formatDateTime } from '../../utils/formatters';
import { humanize, downloadReport } from '../../utils/reportHelpers';
import styles from './reports.module.css';

/** Read-only viewer for a ReportResponseDTO. */
export default function ReportViewModal({ report, categoryName, onClose }) {
  if (!report) return null;

  const meta = [
    ['Type', humanize(report.reportType)],
    ['Category', categoryName || (report.categoryId ? `#${report.categoryId}` : 'All categories')],
    ['Format', report.format || '—'],
    ['Generated by', report.generatedBy || '—'],
    ['Created', formatDateTime(report.createdAt)],
  ];

  return (
    <Modal
      isOpen={!!report}
      onClose={onClose}
      size="lg"
      title={`${humanize(report.reportType)} Report #${report.id}`}
      subtitle="Stored report content"
      footer={
        <>
          <Button variant="secondary" onClick={onClose}>
            Close
          </Button>
          <Button
            id={`report-view-download-${report.id}`}
            variant="primary"
            icon={Download}
            onClick={() => downloadReport(report, categoryName)}
          >
            Download
          </Button>
        </>
      }
    >
      <div className={styles.metaGrid}>
        {meta.map(([label, value]) => (
          <div key={label} className={styles.metaItem}>
            <span className={styles.metaLabel}>{label}</span>
            <span className={styles.metaValue}>{value}</span>
          </div>
        ))}
        <div className={styles.metaItem}>
          <span className={styles.metaLabel}>Status</span>
          <StatusBadge status={report.archived ? 'ARCHIVED' : 'ACTIVE'} label={report.archived ? 'Archived' : 'Active'} />
        </div>
      </div>
      <pre className={styles.contentBox}>{report.content || '(no content)'}</pre>
    </Modal>
  );
}
